name: Lint and Testing

on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  tests:
    runs-on: ubuntu-latest
    container: golang:1.20-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Test with the Go CLI
        run: |
          go test -v -cover -coverprofile coverage.txt ./... && echo "\n==>\033[32m Ok\033[m\n" || exit 1
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
